---
- hosts: localhost
  connection: local
  tasks:
  - name: Download redir template 
    get_url:
      url: https://raw.githubusercontent.com/Cloud-PG/XDC-HA-demo/master/templates/Marathon/redirector.json
      dest: /etc/redirector.json
  - name: Download server template 
    get_url:
      url: https://raw.githubusercontent.com/Cloud-PG/XDC-HA-demo/master/templates/Marathon/server.json
      dest: /etc/server.json
  - name: start xcache redirector
    run_once: true
    uri:
      url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/xcacheredir"
      user: "{{marathon_username}}"
      password: "{{marathon_password}}"
      validate_certs: "no"
      method: PUT
      HEADER_Content-Type: "application/json"
      body: "{{ lookup('template', '/etc/redirector.json') }}"
      body_format: json
    register: result
    until: result.status == 200
    retries: 10
    delay: 20
    changed_when: false

  - name: start xcache server
    run_once: true
    uri:
      url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/xcacheserver"
      user: "{{marathon_username}}"
      password: "{{marathon_password}}"
      validate_certs: "no"
      method: PUT
      HEADER_Content-Type: "application/json"
      body: "{{ lookup('template', '/etc/server.json') }}"
      body_format: json
    register: result
    until: result.status == 200
    retries: 10
    delay: 20
    changed_when: false
