---

kind: Service
apiVersion: v1
metadata:
  name: origin-service
spec:
  type: NodePort
  selector:
    app: origin
  ports:
  - protocol: TCP
    name: xrootd
    port: 1194
    targetPort: 1194
    nodePort: 31194